import { Metadata } from "next";
import React from "react";
export const metadata: Metadata = {
  title: "Create Next App  | About ",
  description: "Generated by create next app",
};
const AboutPage = () => {
  return <div className="container m-auto">AboutPage</div>;
};

export default AboutPage;
